name: Label Checker

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  check_labels:
    name: Check labels for no WIP
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          # Fails build when WIP label exists in Pull Request (for Jira automations)
          none_of: WIP
          repo_token: ${{ secrets.GITHUB_TOKEN }}
